### ISSUE TITLE
Bug: Electron app opens but no window shows up

### ISSUE THREAD

**Issue by acheong08** [benjaminbhollon/verbose-guacamole#19]
**Describe the bug**
```
[  9:24PM ]  [ ac@Antonio:~ ]
 $ z verb
[  9:24PM ]  [ ac@Antonio:~/Github/verbose-guacamole(main✗) ]
 $ npm install         

up to date, audited 595 packages in 3s

55 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (3 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
[  9:24PM ]  [ ac@Antonio:~/Github/verbose-guacamole(main✗) ]
 $ npm start  

> verbose-guacamole@0.3.4 start
> electron-forge start

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Launching Application
```

**Expected behavior**
Start electron properly

**Screenshots**
Verbose-guacamole
<img width="971" alt="Screen Shot 2021-10-27 at 9 27 20 PM" src="https://user-images.githubusercontent.com/36258159/139075018-625f6203-332c-4d27-9cd3-6fb0265c656e.png">
Example of working application:
<img width="967" alt="Screen Shot 2021-10-27 at 9 28 33 PM" src="https://user-images.githubusercontent.com/36258159/139075252-f776bce0-831f-4b94-bc63-3b3d5a2f6672.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Version 21.10

**Additional context**
Other node applications works fine.

**Comment by benjaminbhollon** [comment]
Thanks for creating this! I actually just ran into this the other day, which is why there's no mac OS installer in the latest release yet. I'm working on a fix.

What's interesting is that the application menu appears and functions perfectly fine, and the icon appears as if the app is open. The app is simply not showing. I think it may have been my use of win.hide(), which maybe behaves differently on mac than on windows and linux? I'll test it out tomorrow; I have to borrow a mac to test this stuff.

**Comment by benjaminbhollon** [comment]
To be clear-- the app does run on Linux-based distros and Windows. The Windows installers are missing because I forgot to bump the version in package.json before building! :sweat_smile:

**Comment by benjaminbhollon** [comment]
@acheong08 I'm hopeful that the latest commits fixed the problem-- could you test?

**Comment by benjaminbhollon** [comment]
Confirmed to work now on Mac OS 10.13.6, so I assume it'll work on later versions like yours. I'm finishing up another couple quick fixes and then I'll post an official installer.

**Comment by acheong08** [comment]
Works amazingly. Thanks. 🙏
